import * as vscode from 'vscode';
import { TaskRequest } from '@comu/protocol';

export interface HealthStatus {
    status: 'connected' | 'disconnected' | 'starting';
    details?: string;
}

export interface TaskInfo {
    taskId: string;
    status: string;
}

export const DEFAULT_RUNTIME_BASE_URL = 'http://127.0.0.1:3456';

export class RuntimeClient {
    /**
     * Per-session runtime token. Generated by ServerProcessManager (or taken from
     * COMU_RUNTIME_TOKEN) and required by every runtime route.
     */
    private authToken?: string;

    private get baseUrl(): string {
        const config = vscode.workspace.getConfiguration('comu');
        return config.get<string>('runtime.baseUrl') || DEFAULT_RUNTIME_BASE_URL;
    }

    public setAuthToken(token: string | undefined) {
        this.authToken = token && token.trim() ? token.trim() : undefined;
    }

    public hasAuthToken(): boolean {
        return !!this.authToken;
    }

    public async getHeaders(): Promise<Record<string, string>> {
        const headers: Record<string, string> = {
            'Content-Type': 'application/json'
        };
        if (this.authToken) {
            headers['Authorization'] = `Bearer ${this.authToken}`;
        }
        return headers;
    }

    public async health(): Promise<HealthStatus> {
        const t8 = Date.now();
        console.log('[COMU RUNTIME] T8: runtime health request started');
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 1500);
        try {
            const res = await fetch(`${this.baseUrl}/v1/health`, { headers: await this.getHeaders(), signal: controller.signal });
            clearTimeout(timeout);
            const t9 = Date.now();
            console.log(`[COMU RUNTIME] T9: runtime health response in ${t9 - t8}ms (${res.ok ? 'connected' : 'disconnected'})`);
            if (res.ok) {
                return { status: 'connected' };
            }
            if (res.status === 401) {
                return { status: 'disconnected', details: 'unauthorized' };
            }
            return { status: 'disconnected', details: `Status ${res.status}` };
        } catch (error: any) {
            clearTimeout(timeout);
            const t9 = Date.now();
            console.log(`[COMU RUNTIME] T9: runtime health response in ${t9 - t8}ms (error: ${error.message})`);
            return { status: 'disconnected', details: error.message };
        }
    }

    public async createTask(request: TaskRequest): Promise<TaskInfo> {
        const res = await fetch(`${this.baseUrl}/v1/tasks`, {
            method: 'POST',
            headers: await this.getHeaders(),
            body: JSON.stringify(request)
        });

        if (!res.ok) {
            const err = await res.text().catch(() => 'Unknown error');
            throw new Error(`Failed to create task: ${res.status} ${err}`);
        }

        const data = await res.json() as any;
        return { taskId: data.taskId, status: data.status };
    }

    public async cancelTask(taskId: string): Promise<void> {
        const res = await fetch(`${this.baseUrl}/v1/tasks/${taskId}/cancel`, {
            method: 'POST',
            headers: await this.getHeaders()
        });

        if (!res.ok) {
            throw new Error(`Failed to cancel task: ${res.status}`);
        }
    }

    public getEventStreamUrl(taskId: string): string {
        return `${this.baseUrl}/v1/tasks/${taskId}/events`;
    }

    public async pushConfig(providers: any): Promise<void> {
        const res = await fetch(`${this.baseUrl}/v1/config/providers`, {
            method: 'POST',
            headers: await this.getHeaders(),
            body: JSON.stringify({ providers })
        });
        if (!res.ok) {
            console.error('Failed to push config to runtime');
        }
    }

    public async getDiff(taskId: string, path: string): Promise<{ originalContent?: string; newContent?: string; error?: string }> {
        const res = await fetch(`${this.baseUrl}/v1/tasks/${taskId}/diff?path=${encodeURIComponent(path)}`, {
            headers: await this.getHeaders()
        });
        
        if (!res.ok) {
            throw new Error(`Failed to get diff: ${res.status}`);
        }
        
        return await res.json() as any;
    }

    public async respondInteraction(taskId: string, interactionId: string, response: any): Promise<void> {
        const res = await fetch(`${this.baseUrl}/v1/tasks/${taskId}/interactions/${interactionId}/respond`, {
            method: 'POST',
            headers: await this.getHeaders(),
            body: JSON.stringify({ response })
        });

        if (!res.ok) {
            const err = await res.text().catch(() => 'Unknown error');
            throw new Error(`Failed to respond to interaction: ${res.status} ${err}`);
        }
    }
}
